[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"
broadcast = "broadcast"

# Compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Gas reporting
gas_reports = ["*"]

# Verbosity settings
verbosity = 2

# Fork settings (uncomment and modify for fork testing)
# fork_url = "${RPC_URL}"
# fork_block_number = 16735000

[profile.ci]
verbosity = 3
fuzz_runs = 1000
offline = true

[profile.test]
verbosity = 3
fuzz_runs = 256
src = "test"

[etherscan]
# Your default etherscan API key
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
mainnet = "${RPC_URL}"
sepolia = "${TESTNET_RPC_URL}"
goerli = "${TESTNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
